#!/usr/bin/env bash
#
set -euo pipefail

cd "$(dirname "$0")"

terraform fmt

fmt_docs() {
  ./scripts/terraform-docs-updater "$1"
}

fmt_docs deploy_nixos
fmt_docs google_image_nixos
fmt_docs google_image_nixos_custom

echo "."
